# Generated by Django 4.1.2 on 2022-10-15 11:31

from django.db import migrations, models
import urlshortener.models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_alter_url_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(default=urlshortener.models.create_id, editable=False, max_length=8),
        ),
    ]
